action: broken
packages:
- linux-64/libboost-python-1.88.0-py310ha2bacc8_0.conda
- linux-64/libboost-python-1.88.0-py311h5b7b71f_0.conda
- linux-64/libboost-python-1.88.0-py312hc39e661_0.conda
- linux-64/libboost-python-1.88.0-py313hf0ab243_0.conda
- linux-64/libboost-python-1.88.0-py39hf59e57a_0.conda
- linux-aarch64/libboost-python-1.88.0-py310h9e94223_0.conda
- linux-aarch64/libboost-python-1.88.0-py311hb9acf69_0.conda
- linux-aarch64/libboost-python-1.88.0-py312h4f0fe26_0.conda
- linux-aarch64/libboost-python-1.88.0-py313h0860d92_0.conda
- linux-aarch64/libboost-python-1.88.0-py39hd246915_0.conda
- linux-ppc64le/libboost-python-1.88.0-py310h43a267a_0.conda
- linux-ppc64le/libboost-python-1.88.0-py311hf3d37d3_0.conda
- linux-ppc64le/libboost-python-1.88.0-py312h14f0883_0.conda
- linux-ppc64le/libboost-python-1.88.0-py313h9d95f4f_0.conda
- linux-ppc64le/libboost-python-1.88.0-py39h5e8fc2f_0.conda
- osx-arm64/libboost-python-1.88.0-py310hf1156d2_0.conda
- osx-arm64/libboost-python-1.88.0-py311h8fc16d6_0.conda
- osx-arm64/libboost-python-1.88.0-py312h72cd453_0.conda
- osx-arm64/libboost-python-1.88.0-py313h4e4fec1_0.conda
- osx-arm64/libboost-python-1.88.0-py39h7d68603_0.conda
- osx-64/libboost-python-1.88.0-py310h79e1054_0.conda
- osx-64/libboost-python-1.88.0-py311h10847b1_0.conda
- osx-64/libboost-python-1.88.0-py312hdf63323_0.conda
- osx-64/libboost-python-1.88.0-py313h418fc38_0.conda
- osx-64/libboost-python-1.88.0-py39h5c7665c_0.conda
- win-64/libboost-python-1.88.0-py310h3e8ed56_0.conda
- win-64/libboost-python-1.88.0-py311h9b10771_0.conda
- win-64/libboost-python-1.88.0-py312hbaa7e33_0.conda
- win-64/libboost-python-1.88.0-py313he18703e_0.conda
- win-64/libboost-python-1.88.0-py39h8f1c5a3_0.conda
